version: '3.4'

services:
  app:
    image: binary:auth_added_V1.0
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack



  fullstack-mysql:
    image: mysql:8.0.21
    environment: 
      - MYSQL_USER=${user}
      - MYSQL_PASSWORD=${Password}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${Password}
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge